In [ ]:
'''  
Group by
Aggregate FUnctions -> (mean,max,min,count,sum)

--------------------------------------------------
Order by -> sort values( ascending-=True/false, by= coulmn_name, ignore_index==True/False (default))
rename -. dictonary{'current_column_name': 'replaced_column_name'}
agg -> for anlaysis of multiple aggregate function columns

'''

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('hr_cleaned_data.csv')
df.head()

,Unnamed: 0,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,...,Salary_Label,Salary_label_name,PerformanceScore_id,HireDay_name_id,E_Firstname,E_Middlenae,E_Lastname,M_firstname,M_middlename,M_lastname
0,0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,...,Low Salary,0,0,0,Wilson,K,Adinolfi,Michael,NaN,Albert
1,1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,...,Medium Salary,1,1,1,Karthikeyan,NaN,Ait Sidi,Simon,NaN,Roup
2,2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,...,Low Salary,0,1,0,Sarah,NaN,Akinkuolie,Kissy,NaN,Sullivan
3,3,Alagbe Trina,10088,1,1,0,1,5,3,0,...,Low Salary,0,1,1,Trina,NaN,Alagbe,Elijiah,NaN,Gray
4,4,Anderson Carol,10069,0,2,0,5,5,3,0,...,Low Salary,0,1,1,Carol,NaN,Anderson,Webster,NaN,Butler

In [3]:
df.columns

Index(['Unnamed: 0', 'Employee_Name', 'EmpID', 'MarriedID', 'MaritalStatusID',
       'GenderID', 'EmpStatusID', 'DeptID', 'PerfScoreID',
       'FromDiversityJobFairID', 'Salary', 'Termd', 'PositionID', 'Position',
       'State', 'Zip', 'DOB', 'Gender', 'MaritalDesc', 'CitizenDesc',
       'HispanicLatino', 'RaceDesc', 'DateofHire', 'DateofTermination',
       'TermReason', 'EmploymentStatus', 'Department', 'ManagerName',
       'ManagerID', 'RecruitmentSource', 'PerformanceScore',
       'EngagementSurvey', 'EmpSatisfaction', 'SpecialProjectsCount',
       'LastPerformanceReview_Date', 'DaysLateLast30', 'Absences', 'HireYear',
       'HireMonth', 'HireDay', 'HireMonth_name', 'HireDay_name',
       'Salary_Label', 'Salary_label_name', 'PerformanceScore_id',
       'HireDay_name_id', 'E_Firstname', 'E_Middlenae', 'E_Lastname',
       'M_firstname', 'M_middlename', 'M_lastname'],
      dtype='str')

In [ ]:
# find total employees hired through each Recruitment Source

'''  
syntax of Groupby
----------------------

-> dataframe.groupby(column_name)[column_name].agg_funciton()

'''

In [4]:
df['RecruitmentSource'].unique()

<StringArray>
[               'LinkedIn',                  'Indeed',
           'Google Search',       'Employee Referral',
      'Diversity Job Fair', 'On-line Web application',
           'CareerBuilder',                 'Website',
                   'Other']
Length: 9, dtype: str

In [ ]:
emp_recruitment=df.groupby('RecruitmentSource')['EmpID'].count()  # counting EmpID for each recruitment source

In [8]:
emp_recruitment

RecruitmentSource
CareerBuilder              23
Diversity Job Fair         29
Employee Referral          31
Google Search              49
Indeed                     87
LinkedIn                   76
On-line Web application     1
Other                       2
Website                    13
Name: EmpID, dtype: int64

In [ ]:
emp_recruitment=df.groupby('RecruitmentSource')['EmpID'].count().reset_index()
emp_recruitment     # showing index ---- key value

         RecruitmentSource  EmpID
0            CareerBuilder     23
1       Diversity Job Fair     29
2        Employee Referral     31
3            Google Search     49
4                   Indeed     87
5                 LinkedIn     76
6  On-line Web application      1
7                    Other      2
8                  Website     13

In [ ]:
emp_recruitment=df.groupby('RecruitmentSource')['EmpID'].count().reset_index().rename(
    columns={'EmpID':'Total Employees','RecruitmentSource':'Recruitment Source'}
)
emp_recruitment     # nwo renaming the column names

        Recruitment Source  Total Employees
0            CareerBuilder               23
1       Diversity Job Fair               29
2        Employee Referral               31
3            Google Search               49
4                   Indeed               87
5                 LinkedIn               76
6  On-line Web application                1
7                    Other                2
8                  Website               13

In [ ]:
# all above analysis can be done at one with sorting like here

emp_recruitment=df.groupby('RecruitmentSource')['EmpID'].count().reset_index().rename(
    columns={'EmpID':'Total Employees','RecruitmentSource':'Recruitment Source'}
).sort_values(ascending=True,by='Total Employees',ignore_index=True)
emp_recruitment

        Recruitment Source  Total Employees
0  On-line Web application                1
1                    Other                2
2                  Website               13
3            CareerBuilder               23
4       Diversity Job Fair               29
5        Employee Referral               31
6            Google Search               49
7                 LinkedIn               76
8                   Indeed               87

In [16]:
emp_recruitment=df.groupby('RecruitmentSource')['EmpID'].count()
format_data=emp_recruitment.to_markdown(numalign='center',stralign='center')

print(format_data)

|    RecruitmentSource    |  EmpID  |
|:-----------------------:|:-------:|
|      CareerBuilder      |   23    |
|   Diversity Job Fair    |   29    |
|    Employee Referral    |   31    |
|      Google Search      |   49    |
|         Indeed          |   87    |
|        LinkedIn         |   76    |
| On-line Web application |    1    |
|          Other          |    2    |
|         Website         |   13    |

In [ ]:
# find total employees hired through each recruitment Source and Gender  also salary_label

hire_emp=df.groupby(['RecruitmentSource','Gender','Salary_Label'])['EmpID'].count().reset_index().rename(
    columns={'EmpID':'Total Employees'}
)
hire_emp

          RecruitmentSource Gender   Salary_Label  Total Employees
0             CareerBuilder      F     Low Salary               15
1             CareerBuilder      F  Medium Salary                1
2             CareerBuilder      M     Low Salary                5
3             CareerBuilder      M  Medium Salary                2
4        Diversity Job Fair      F     Low Salary               13
5        Diversity Job Fair      F  Medium Salary                2
6        Diversity Job Fair      M    High Salary                1
7        Diversity Job Fair      M     Low Salary                5
8        Diversity Job Fair      M  Medium Salary                8
9         Employee Referral      F    High Salary                1
10        Employee Referral      F     Low Salary                4
11        Employee Referral      F  Medium Salary                6
12        Employee Referral      M     Low Salary               11
13        Employee Referral      M  Medium Salary                9
14            Google Search      F     Low Salary               28
15            Google Search      F  Medium Salary                5
16            Google Search      M     Low Salary               14
17            Google Search      M  Medium Salary                2
18                   Indeed      F    High Salary                2
19                   Indeed      F     Low Salary               35
20                   Indeed      F  Medium Salary               13
21                   Indeed      M    High Salary                2
22                   Indeed      M     Low Salary               20
23                   Indeed      M  Medium Salary               15
24                 LinkedIn      F    High Salary                1
25                 LinkedIn      F     Low Salary               35
26                 LinkedIn      F  Medium Salary                8
27                 LinkedIn      M     Low Salary               24
28                 LinkedIn      M  Medium Salary                8
29  On-line Web application      M     Low Salary                1
30                    Other      F  Medium Salary                1
31                    Other      M     Low Salary                1
32                  Website      F     Low Salary                5
33                  Website      F  Medium Salary                1
34                  Website      M     Low Salary                6
35                  Website      M  Medium Salary                1

In [44]:
# find total employees hired and total salary distribution of employees through each recruitment Source and Gender

# using agg to aggregate multiple columns

hire_emp_salary=df.groupby(['RecruitmentSource','Gender']).agg(
    Total_Employees= ('EmpID','count'),
    Total_salary=('Salary','sum'),
    Maximum_Salary=('Salary','max'),
    Mimimum_Salary=('Salary','min')
).reset_index()


hire_emp_salary['Total_salary']= hire_emp_salary['Total_salary'].map('Rs.{:,.2f}'.format)
hire_emp_salary

,RecruitmentSource,Gender,Total_Employees,Total_salary,Maximum_Salary,Mimimum_Salary
0,CareerBuilder,F,16,"Rs.989,848.00",101199,46335
1,CareerBuilder,M,7,"Rs.470,250.00",93046,46837
2,Diversity Job Fair,F,15,"Rs.906,352.00",106367,47434
3,Diversity Job Fair,M,14,"Rs.1,188,934.00",157000,47211
4,Employee Referral,F,11,"Rs.970,170.00",220450,45069
5,Employee Referral,M,20,"Rs.1,443,578.00",113999,46664
6,Google Search,F,33,"Rs.2,031,361.00",110000,45433
7,Google Search,M,16,"Rs.945,136.00",77692,46428
8,Indeed,F,50,"Rs.3,626,377.00",250000,46430
9,Indeed,M,37,"Rs.2,941,753.00",178000,50178
10,LinkedIn,F,44,"Rs.2,943,411.00",180000,45046
11,LinkedIn,M,32,"Rs.1,989,241.00",103613,45115
12,On-line Web application,M,1,"Rs.52,505.00",52505,52505
13,Other,F,1,"Rs.99,351.00",99351,99351
14,Other,M,1,"Rs.67,176.00",67176,67176
15,Website,F,6,"Rs.363,594.00",77915,51920
16,Website,M,7,"Rs.436,396.00",70468,55140

In [45]:
def addCurrency(dataframe, prefix, *args):
    for col in args:
        dataframe[col]=dataframe[col].map(f'{prefix}''{:,.2f}'.format)

In [ ]:
hire_emp_salary=df.groupby(['RecruitmentSource','Gender']).agg(
    Total_Employees= ('EmpID','count'),
    Total_salary=('Salary','sum'),
    Maximum_Salary=('Salary','max'),
    Mimimum_Salary=('Salary','min')
).reset_index()


addCurrency(hire_emp_salary,'Rs.','Total_salary')
addCurrency(hire_emp_salary,'Rs.','Maximum_Salary')
addCurrency(hire_emp_salary,'Rs.','Minimum_alary')
hire_emp_salary

,RecruitmentSource,Gender,Total_Employees,Total_salary,Maximum_Salary,Mimimum_Salary
0,CareerBuilder,F,16,"Rs.989,848.00",101199,46335
1,CareerBuilder,M,7,"Rs.470,250.00",93046,46837
2,Diversity Job Fair,F,15,"Rs.906,352.00",106367,47434
3,Diversity Job Fair,M,14,"Rs.1,188,934.00",157000,47211
4,Employee Referral,F,11,"Rs.970,170.00",220450,45069
5,Employee Referral,M,20,"Rs.1,443,578.00",113999,46664
6,Google Search,F,33,"Rs.2,031,361.00",110000,45433
7,Google Search,M,16,"Rs.945,136.00",77692,46428
8,Indeed,F,50,"Rs.3,626,377.00",250000,46430
9,Indeed,M,37,"Rs.2,941,753.00",178000,50178
10,LinkedIn,F,44,"Rs.2,943,411.00",180000,45046
11,LinkedIn,M,32,"Rs.1,989,241.00",103613,45115
12,On-line Web application,M,1,"Rs.52,505.00",52505,52505
13,Other,F,1,"Rs.99,351.00",99351,99351
14,Other,M,1,"Rs.67,176.00",67176,67176
15,Website,F,6,"Rs.363,594.00",77915,51920
16,Website,M,7,"Rs.436,396.00",70468,55140