In [ ]:
'''  
NUll values
--------------
NaN -> not a number == object,integer,float, boolean
NaT -> not a time == date/time

'''

Data Cleaning

In [ ]:
'''  
Process of Data Cleaning
------------------------------
1. Handle Null values
   - Fill Null values
      ->fillna()

      ----------------------------
      Continuous data -> mean /median
      -------------------------------
      To determine which one to use mean/median
      -> Skewness -> use .skew()
          -> 0 to 0.5 (Normal distribution/ Bell curve ) = mean
          -> less than 0 (Left Skewness/ Negative Skewness) or more than0.5 ( Right skewness/ Positive Skewness)=median

       -> calculate mean and median
           if both values are equal or almost equal = mean value
                       or else = median value

        -> fill custom record if any values ar enot correct to fill
       
        ----------------------------
        Categorical/ Discrete data -> mode
        ------------------------------

   - Drop NUll values
       ->dropna()
       -> if data comsists of more than 70% null values then drop column.

2. Remove duplicate records
   - find duplicate records -> duplicated()
   - remove duplicate records -> drop_duplicates()

3. Remove unwanted data
  - remove unwanted characters
    -> str.replace()

  - remove whitespace
   -> str.strip()

  - text transformation
    ->  str.upper() / str.lower() / str.capitalize()

'''

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Dataset/Employees.csv')
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0

### Drop Null values

In [13]:
# data information
df.info()

<class 'pandas.DataFrame'>
Index: 34 entries, 45 to 79
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     34 non-null     int64
 1   FIRST_NAME      34 non-null     str
 2   LAST_NAME       34 non-null     str
 3   EMAIL           34 non-null     str
 4   PHONE_NUMBER    34 non-null     str
 5   HIRE_DATE       34 non-null     str
 6   JOB_ID          34 non-null     str
 7   SALARY          34 non-null     int64
 8   COMMISSION_PCT  34 non-null     float64
 9   MANAGER_ID      34 non-null     float64
 10  DEPARTMENT_ID   34 non-null     float64
dtypes: float64(3), int64(2), str(6)
memory usage: 3.2 KB

In [4]:
# to check null values
df.isnull()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,False,False,False,False,False,False,False,False,True,True,False
1,False,False,False,False,False,False,False,False,True,False,False
2,False,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,True,False,False
4,False,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...
106,False,False,False,False,False,False,False,False,True,False,False
107,False,False,False,False,False,False,False,False,True,False,False
108,False,False,False,False,False,False,False,False,True,False,False
109,False,False,False,False,False,False,False,False,True,False,False
110,False,False,False,False,False,False,False,False,True,False,False

In [36]:
#to get sum of nul values for each column


df.isnull().sum()

EMPLOYEE_ID       0
FIRST_NAME        0
LAST_NAME         0
EMAIL             0
PHONE_NUMBER      0
HIRE_DATE         0
JOB_ID            0
SALARY            0
COMMISSION_PCT    0
MANAGER_ID        0
DEPARTMENT_ID     0
dtype: int64

In [37]:
'''  
to change data permanently
  inplace - True / flase ( default)

Dropna Arguments
-----------------
1. inplace = True/ Flase
2. axis = 0 ( row) / 1 ( column)
3. how = any ( default) / all   --> any means anyone data in row or column is null then entire row/ column is dropped
                                --> all means if all data in row/ column is null then entire row/ column is dropped 


'''



df.dropna(axis=0,how='any',inplace=True)

In [38]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,0.22,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,0.22,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,0.22,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,0.22,103.0,60.0
5,105,David,Austin,DAUSTIN,590.423.4569,6/25/2005,IT_PROG,4800,0.22,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,0.22,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,0.22,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,0.22,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,0.22,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,0.22,205.0,110.0

In [42]:
# drop particular row --> use indexing
df.drop(index=0)

KeyError: '[0] not found in axis'

In [ ]:
# dropping particular columns

df.drop(columns='FIRST_NAME')

,EMPLOYEE_ID,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...
106,206,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

### Fill Null Values

In [ ]:
commission_skew= df['COMMISSION_PCT'].skew()
commission_skew

np.float64(0.09661736135041571)

In [ ]:
commission_mean= round(df['COMMISSION_PCT'].mean(),2)
commission_median= df['COMMISSION_PCT'].median()

print(f'Commission mean ={ commission_mean}')
print(f'Commission Median= {commission_median}')

Commission mean =0.22
Commission Median= 0.2

In [ ]:
df['COMMISSION_PCT'].fillna(commission_mean)  # not permanenetly filled

0      0.22
1      0.22
2      0.22
3      0.22
4      0.22
       ...
106    0.22
107    0.22
108    0.22
109    0.22
110    0.22
Name: COMMISSION_PCT, Length: 111, dtype: float64

In [ ]:
df["COMMISSION_PCT"]

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
106   NaN
107   NaN
108   NaN
109   NaN
110   NaN
Name: COMMISSION_PCT, Length: 111, dtype: float64

In [ ]:
# permanently filleed
#  df['COMMISSION_PCT'].fillna(commission_mean,inplace= True)
#df['COMMISSION_PCT']=df['COMMISSION_PCT'].fillna(commission_mean,inplace= True) # rreplcing the changes to same column
df.fillna({'COMMISSION_PCT': commission_mean},inplace= True)

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,0.22,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,0.22,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,0.22,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,0.22,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,0.22,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,0.22,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,0.22,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,0.22,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,0.22,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,0.22,205.0,110.0

In [ ]:
df['COMMISSION_PCT'].unique()

array([0.22, 0.4 , 0.3 , 0.2 , 0.25, 0.15, 0.35, 0.1 ])

In [ ]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,0.22,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,0.22,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,0.22,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,0.22,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,0.22,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,0.22,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,0.22,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,0.22,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,0.22,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,0.22,205.0,110.0

### Discrete data

In [ ]:
mgr_mode=df['MANAGER_ID'].mode()[0]
mgr_mode

0    100.0
Name: MANAGER_ID, dtype: float64

In [40]:
dep_mode=df['DEPARTMENT_ID'].mode()[0]
dep_mode

np.float64(50.0)

In [41]:
df['MANAGER_ID'].fillna(mgr_mode, inplace=True)
df['DEPARTMENT_ID'].fillna(dep_mode, inplace= True)

C:\Users\HP\AppData\Local\Temp\ipykernel_14728\3107165323.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['MANAGER_ID'].fillna(mgr_mode, inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_14728\3107165323.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['DEPARTMENT_ID'].fillna(dep_mode, inplace= True)

1       90.0
2       90.0
3       60.0
4       60.0
5       60.0
       ...
106    110.0
107     40.0
108     70.0
109    110.0
110    110.0
Name: DEPARTMENT_ID, Length: 109, dtype: float64

In [43]:
ff= pd.read_csv('Dataset/Fraud Detection Dataset.csv')
ff.head()

,Transaction_ID,User_ID,Transaction_Amount,Transaction_Type,Time_of_Transaction,Device_Used,Location,Previous_Fraudulent_Transactions,Account_Age,Number_of_Transactions_Last_24H,Payment_Method,Fraudulent
0,T1,4174,1292.76,ATM Withdrawal,16.0,Tablet,San Francisco,0,119,13,Debit Card,0
1,T2,4507,1554.58,ATM Withdrawal,13.0,Mobile,New York,4,79,3,Credit Card,0
2,T3,1860,2395.02,ATM Withdrawal,NaN,Mobile,NaN,3,115,9,NaN,0
3,T4,2294,100.10,Bill Payment,15.0,Desktop,Chicago,4,3,4,UPI,0
4,T5,2130,1490.50,POS Payment,19.0,Mobile,San Francisco,2,57,7,Credit Card,0

In [44]:
ff.info()

<class 'pandas.DataFrame'>
RangeIndex: 51000 entries, 0 to 50999
Data columns (total 12 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Transaction_ID                    51000 non-null  str
 1   User_ID                           51000 non-null  int64
 2   Transaction_Amount                48480 non-null  float64
 3   Transaction_Type                  51000 non-null  str
 4   Time_of_Transaction               48448 non-null  float64
 5   Device_Used                       48527 non-null  str
 6   Location                          48453 non-null  str
 7   Previous_Fraudulent_Transactions  51000 non-null  int64
 8   Account_Age                       51000 non-null  int64
 9   Number_of_Transactions_Last_24H   51000 non-null  int64
 10  Payment_Method                    48531 non-null  str
 11  Fraudulent                        51000 non-null  int64
dtypes: float64(2), int64(5), str(5)
memory usage: 4.7 MB

In [47]:
ff.isnull().sum()

Transaction_ID                         0
User_ID                                0
Transaction_Amount                  2520
Transaction_Type                       0
Time_of_Transaction                 2552
Device_Used                         2473
Location                            2547
Previous_Fraudulent_Transactions       0
Account_Age                            0
Number_of_Transactions_Last_24H        0
Payment_Method                      2469
Fraudulent                             0
dtype: int64

### Duplicate data removal

In [60]:
# find duplicate values  -> duplicated(subset=[column_name])
#                         -> drop_duplicates(subset=[column_name],keep='first'/'last')

duplicate_data=ff[ff.duplicated(subset=['Transaction_ID'])]

duplicate_data

,Transaction_ID,User_ID,Transaction_Amount,Transaction_Type,Time_of_Transaction,Device_Used,Location,Previous_Fraudulent_Transactions,Account_Age,Number_of_Transactions_Last_24H,Payment_Method,Fraudulent
50000,T33554,2669,2425.71,Bank Transfer,14.0,Tablet,Seattle,2,40,7,UPI,0
50001,T9428,1001,2448.53,Bank Transfer,19.0,Mobile,San Francisco,4,7,3,NaN,0
50002,T200,3790,4429.89,ATM Withdrawal,17.0,NaN,Miami,1,39,6,UPI,1
50003,T12448,1743,108.00,ATM Withdrawal,15.0,Tablet,Los Angeles,3,67,9,Credit Card,0
50004,T39490,4329,2320.30,ATM Withdrawal,4.0,Desktop,Los Angeles,3,12,10,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...
50995,T33982,2339,3112.51,Bill Payment,15.0,Mobile,New York,0,7,8,Debit Card,0
50996,T31261,2152,2897.15,Online Purchase,3.0,Mobile,Miami,1,75,11,Net Banking,1
50997,T12293,3345,2204.43,POS Payment,18.0,Mobile,San Francisco,3,73,5,Credit Card,0
50998,T42287,1518,4787.17,POS Payment,19.0,Tablet,New York,2,108,14,Net Banking,0
50999,T13665,2315,814.72,POS Payment,3.0,Tablet,Los Angeles,0,50,10,Invalid Method,0

In [61]:
fraud_sample=ff.drop_duplicates(subset=['Transaction_ID'])
fraud_sample

,Transaction_ID,User_ID,Transaction_Amount,Transaction_Type,Time_of_Transaction,Device_Used,Location,Previous_Fraudulent_Transactions,Account_Age,Number_of_Transactions_Last_24H,Payment_Method,Fraudulent
0,T1,4174,1292.76,ATM Withdrawal,16.0,Tablet,San Francisco,0,119,13,Debit Card,0
1,T2,4507,1554.58,ATM Withdrawal,13.0,Mobile,New York,4,79,3,Credit Card,0
2,T3,1860,2395.02,ATM Withdrawal,NaN,Mobile,NaN,3,115,9,NaN,0
3,T4,2294,100.10,Bill Payment,15.0,Desktop,Chicago,4,3,4,UPI,0
4,T5,2130,1490.50,POS Payment,19.0,Mobile,San Francisco,2,57,7,Credit Card,0
...,...,...,...,...,...,...,...,...,...,...,...,...
49995,T49996,1296,1844.08,Online Purchase,22.0,Desktop,Los Angeles,1,47,4,Credit Card,0
49996,T49997,3592,3274.95,POS Payment,15.0,Mobile,San Francisco,2,81,1,UPI,0
49997,T49998,3536,647.11,Bill Payment,11.0,Unknown Device,Miami,2,96,3,Debit Card,0
49998,T49999,2019,2446.65,POS Payment,9.0,Tablet,Boston,3,117,13,UPI,0
49999,T50000,3262,2867.43,Bank Transfer,14.0,Desktop,Miami,4,73,11,UPI,0

### Clean Data

In [62]:
ff['Transaction_Amount'].skew()

np.float64(8.454478956647055)

In [63]:
median_amount= ff['Transaction_Amount'].median()
median_amount

np.float64(2524.1000000000004)

In [64]:
ff.fillna({'Transaction_Amount': median_amount}, inplace= True)

,Transaction_ID,User_ID,Transaction_Amount,Transaction_Type,Time_of_Transaction,Device_Used,Location,Previous_Fraudulent_Transactions,Account_Age,Number_of_Transactions_Last_24H,Payment_Method,Fraudulent
0,T1,4174,1292.76,ATM Withdrawal,16.0,Tablet,San Francisco,0,119,13,Debit Card,0
1,T2,4507,1554.58,ATM Withdrawal,13.0,Mobile,New York,4,79,3,Credit Card,0
2,T3,1860,2395.02,ATM Withdrawal,NaN,Mobile,NaN,3,115,9,NaN,0
3,T4,2294,100.10,Bill Payment,15.0,Desktop,Chicago,4,3,4,UPI,0
4,T5,2130,1490.50,POS Payment,19.0,Mobile,San Francisco,2,57,7,Credit Card,0
...,...,...,...,...,...,...,...,...,...,...,...,...
50995,T33982,2339,3112.51,Bill Payment,15.0,Mobile,New York,0,7,8,Debit Card,0
50996,T31261,2152,2897.15,Online Purchase,3.0,Mobile,Miami,1,75,11,Net Banking,1
50997,T12293,3345,2204.43,POS Payment,18.0,Mobile,San Francisco,3,73,5,Credit Card,0
50998,T42287,1518,4787.17,POS Payment,19.0,Tablet,New York,2,108,14,Net Banking,0
50999,T13665,2315,814.72,POS Payment,3.0,Tablet,Los Angeles,0,50,10,Invalid Method,0

In [69]:
ff.isnull().sum()

Transaction_ID                         0
User_ID                                0
Transaction_Amount                     0
Transaction_Type                       0
Time_of_Transaction                 2552
Device_Used                         2473
Location                            2547
Previous_Fraudulent_Transactions       0
Account_Age                            0
Number_of_Transactions_Last_24H        0
Payment_Method                      2469
Fraudulent                             0
dtype: int64

In [73]:
mode_time= ff['Time_of_Transaction'].mode()[0]
mode_time

np.float64(18.0)

In [74]:
ff.fillna({'Time_of_Transaction': mode_time},inplace=True)

,Transaction_ID,User_ID,Transaction_Amount,Transaction_Type,Time_of_Transaction,Device_Used,Location,Previous_Fraudulent_Transactions,Account_Age,Number_of_Transactions_Last_24H,Payment_Method,Fraudulent
0,T1,4174,1292.76,ATM Withdrawal,16.0,Tablet,San Francisco,0,119,13,Debit Card,0
1,T2,4507,1554.58,ATM Withdrawal,13.0,Mobile,New York,4,79,3,Credit Card,0
2,T3,1860,2395.02,ATM Withdrawal,18.0,Mobile,NaN,3,115,9,NaN,0
3,T4,2294,100.10,Bill Payment,15.0,Desktop,Chicago,4,3,4,UPI,0
4,T5,2130,1490.50,POS Payment,19.0,Mobile,San Francisco,2,57,7,Credit Card,0
...,...,...,...,...,...,...,...,...,...,...,...,...
50995,T33982,2339,3112.51,Bill Payment,15.0,Mobile,New York,0,7,8,Debit Card,0
50996,T31261,2152,2897.15,Online Purchase,3.0,Mobile,Miami,1,75,11,Net Banking,1
50997,T12293,3345,2204.43,POS Payment,18.0,Mobile,San Francisco,3,73,5,Credit Card,0
50998,T42287,1518,4787.17,POS Payment,19.0,Tablet,New York,2,108,14,Net Banking,0
50999,T13665,2315,814.72,POS Payment,3.0,Tablet,Los Angeles,0,50,10,Invalid Method,0

In [75]:
ff.isnull().sum()

Transaction_ID                         0
User_ID                                0
Transaction_Amount                     0
Transaction_Type                       0
Time_of_Transaction                    0
Device_Used                         2473
Location                            2547
Previous_Fraudulent_Transactions       0
Account_Age                            0
Number_of_Transactions_Last_24H        0
Payment_Method                      2469
Fraudulent                             0
dtype: int64

In [76]:
ff['Device_Used'].unique()

<StringArray>
['Tablet', 'Mobile', 'Desktop', nan, 'Unknown Device']
Length: 5, dtype: str

In [77]:
ff.fillna({'Device_Used':'Unknown Device'}, inplace= True)

,Transaction_ID,User_ID,Transaction_Amount,Transaction_Type,Time_of_Transaction,Device_Used,Location,Previous_Fraudulent_Transactions,Account_Age,Number_of_Transactions_Last_24H,Payment_Method,Fraudulent
0,T1,4174,1292.76,ATM Withdrawal,16.0,Tablet,San Francisco,0,119,13,Debit Card,0
1,T2,4507,1554.58,ATM Withdrawal,13.0,Mobile,New York,4,79,3,Credit Card,0
2,T3,1860,2395.02,ATM Withdrawal,18.0,Mobile,NaN,3,115,9,NaN,0
3,T4,2294,100.10,Bill Payment,15.0,Desktop,Chicago,4,3,4,UPI,0
4,T5,2130,1490.50,POS Payment,19.0,Mobile,San Francisco,2,57,7,Credit Card,0
...,...,...,...,...,...,...,...,...,...,...,...,...
50995,T33982,2339,3112.51,Bill Payment,15.0,Mobile,New York,0,7,8,Debit Card,0
50996,T31261,2152,2897.15,Online Purchase,3.0,Mobile,Miami,1,75,11,Net Banking,1
50997,T12293,3345,2204.43,POS Payment,18.0,Mobile,San Francisco,3,73,5,Credit Card,0
50998,T42287,1518,4787.17,POS Payment,19.0,Tablet,New York,2,108,14,Net Banking,0
50999,T13665,2315,814.72,POS Payment,3.0,Tablet,Los Angeles,0,50,10,Invalid Method,0

In [78]:
ff.isnull().sum()

Transaction_ID                         0
User_ID                                0
Transaction_Amount                     0
Transaction_Type                       0
Time_of_Transaction                    0
Device_Used                            0
Location                            2547
Previous_Fraudulent_Transactions       0
Account_Age                            0
Number_of_Transactions_Last_24H        0
Payment_Method                      2469
Fraudulent                             0
dtype: int64

In [79]:
ff['Location'].unique()

<StringArray>
['San Francisco',      'New York',             nan,       'Chicago',
        'Boston',       'Houston',         'Miami',   'Los Angeles',
       'Seattle']
Length: 9, dtype: str

In [ ]:
ff.fillna({'Location': 'Unknown Location'}, inplace =True)       # filling custom data "unknown location"

,Transaction_ID,User_ID,Transaction_Amount,Transaction_Type,Time_of_Transaction,Device_Used,Location,Previous_Fraudulent_Transactions,Account_Age,Number_of_Transactions_Last_24H,Payment_Method,Fraudulent
0,T1,4174,1292.76,ATM Withdrawal,16.0,Tablet,San Francisco,0,119,13,Debit Card,0
1,T2,4507,1554.58,ATM Withdrawal,13.0,Mobile,New York,4,79,3,Credit Card,0
2,T3,1860,2395.02,ATM Withdrawal,18.0,Mobile,Unknown Location,3,115,9,NaN,0
3,T4,2294,100.10,Bill Payment,15.0,Desktop,Chicago,4,3,4,UPI,0
4,T5,2130,1490.50,POS Payment,19.0,Mobile,San Francisco,2,57,7,Credit Card,0
...,...,...,...,...,...,...,...,...,...,...,...,...
50995,T33982,2339,3112.51,Bill Payment,15.0,Mobile,New York,0,7,8,Debit Card,0
50996,T31261,2152,2897.15,Online Purchase,3.0,Mobile,Miami,1,75,11,Net Banking,1
50997,T12293,3345,2204.43,POS Payment,18.0,Mobile,San Francisco,3,73,5,Credit Card,0
50998,T42287,1518,4787.17,POS Payment,19.0,Tablet,New York,2,108,14,Net Banking,0
50999,T13665,2315,814.72,POS Payment,3.0,Tablet,Los Angeles,0,50,10,Invalid Method,0

In [81]:
ff.isnull().sum()

Transaction_ID                         0
User_ID                                0
Transaction_Amount                     0
Transaction_Type                       0
Time_of_Transaction                    0
Device_Used                            0
Location                               0
Previous_Fraudulent_Transactions       0
Account_Age                            0
Number_of_Transactions_Last_24H        0
Payment_Method                      2469
Fraudulent                             0
dtype: int64

In [82]:
ff['Payment_Method'].unique()

<StringArray>
['Debit Card', 'Credit Card', nan, 'UPI', 'Net Banking', 'Invalid Method']
Length: 6, dtype: str

In [83]:
ff.fillna({'Payment_Method':'Invalid Method'}, inplace= True)

,Transaction_ID,User_ID,Transaction_Amount,Transaction_Type,Time_of_Transaction,Device_Used,Location,Previous_Fraudulent_Transactions,Account_Age,Number_of_Transactions_Last_24H,Payment_Method,Fraudulent
0,T1,4174,1292.76,ATM Withdrawal,16.0,Tablet,San Francisco,0,119,13,Debit Card,0
1,T2,4507,1554.58,ATM Withdrawal,13.0,Mobile,New York,4,79,3,Credit Card,0
2,T3,1860,2395.02,ATM Withdrawal,18.0,Mobile,Unknown Location,3,115,9,Invalid Method,0
3,T4,2294,100.10,Bill Payment,15.0,Desktop,Chicago,4,3,4,UPI,0
4,T5,2130,1490.50,POS Payment,19.0,Mobile,San Francisco,2,57,7,Credit Card,0
...,...,...,...,...,...,...,...,...,...,...,...,...
50995,T33982,2339,3112.51,Bill Payment,15.0,Mobile,New York,0,7,8,Debit Card,0
50996,T31261,2152,2897.15,Online Purchase,3.0,Mobile,Miami,1,75,11,Net Banking,1
50997,T12293,3345,2204.43,POS Payment,18.0,Mobile,San Francisco,3,73,5,Credit Card,0
50998,T42287,1518,4787.17,POS Payment,19.0,Tablet,New York,2,108,14,Net Banking,0
50999,T13665,2315,814.72,POS Payment,3.0,Tablet,Los Angeles,0,50,10,Invalid Method,0

In [84]:
ff.isnull().sum()

Transaction_ID                      0
User_ID                             0
Transaction_Amount                  0
Transaction_Type                    0
Time_of_Transaction                 0
Device_Used                         0
Location                            0
Previous_Fraudulent_Transactions    0
Account_Age                         0
Number_of_Transactions_Last_24H     0
Payment_Method                      0
Fraudulent                          0
dtype: int64

### clean code as repetedly same code is being written

In [ ]:
# function to clean code

def clean_data(dataframe, column, data):
    dataframe.fillna({column:data}, inplace=True)

In [86]:
clean_data(ff,'Transaction_Amount',median_amount)

In [87]:
clean_data(ff,'Time_of_Transaction',mode_time)

### Remove unwanted charcters

In [ ]:
import pandas as pd
hr = pd.read_csv('Dataset/HR_Dataset Refresh.csv')
hr.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2

In [3]:
hr.isnull().sum()

Employee_Name                   0
EmpID                           0
MarriedID                       0
MaritalStatusID                 0
GenderID                        0
EmpStatusID                     0
DeptID                          0
PerfScoreID                     0
FromDiversityJobFairID          0
Salary                          0
Termd                           0
PositionID                      0
Position                        0
State                           0
Zip                             0
DOB                             0
Gender                          0
MaritalDesc                     0
CitizenDesc                     0
HispanicLatino                  0
RaceDesc                        0
DateofHire                      0
DateofTermination             386
TermReason                      0
EmploymentStatus                0
Department                      0
ManagerName                     0
ManagerID                       8
RecruitmentSource               0
PerformanceScore                0
EngagementSurvey                0
EmpSatisfaction                 0
SpecialProjectsCount            0
LastPerformanceReview_Date      0
DaysLateLast30                  0
Absences                        0
dtype: int64

Clean Data

In [12]:
mgr_mode=hr['ManagerID'].mode()[0]

In [13]:
hr.fillna({'ManagerID': mgr_mode },inplace=True)

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,"Woodson, Jason",10135,0,0,1,1,5,3,0,65893,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,4.07,4,0,2/28/2019,0,13
326,"Ybarra, Catherine",10301,0,0,0,5,5,1,0,48513,...,Brannon Miller,12.0,Google Search,PIP,3.20,2,0,9/2/2015,5,4
327,"Zamora, Jennifer",10010,0,0,0,1,3,4,0,220450,...,Janet King,2.0,Employee Referral,Exceeds,4.60,5,6,2/21/2019,0,16
328,"Zhou, Julia",10043,0,0,0,1,3,3,0,89292,...,Simon Roup,4.0,Employee Referral,Fully Meets,5.00,3,5,2/1/2019,0,11
329,"Zima, Colleen",10271,0,4,0,1,5,3,0,45046,...,David Stanley,14.0,LinkedIn,Fully Meets,4.50,5,0,1/30/2019,0,2

Duplicate datA

In [14]:
duplicate_hrdata=hr[hr.duplicated(subset=['EmpID'])]
duplicate_hrdata

Empty DataFrame
Columns: [Employee_Name, EmpID, MarriedID, MaritalStatusID, GenderID, EmpStatusID, DeptID, PerfScoreID, FromDiversityJobFairID, Salary, Termd, PositionID, Position, State, Zip, DOB, Gender, MaritalDesc, CitizenDesc, HispanicLatino, RaceDesc, DateofHire, DateofTermination, TermReason, EmploymentStatus, Department, ManagerName, ManagerID, RecruitmentSource, PerformanceScore, EngagementSurvey, EmpSatisfaction, SpecialProjectsCount, LastPerformanceReview_Date, DaysLateLast30, Absences]
Index: []

[0 rows x 36 columns]

In [15]:
empid= int(input('Enter an id:'))
data=hr[hr['EmpID']== empid]
data

ValueError: invalid literal for int() with base 10: 'Escape'

In [ ]:
hr=hr.drop_duplicates(subset=['EmpID'])
hr

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,"Woodson, Jason",10135,0,0,1,1,5,3,0,65893,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,4.07,4,0,2/28/2019,0,13
326,"Ybarra, Catherine",10301,0,0,0,5,5,1,0,48513,...,Brannon Miller,12.0,Google Search,PIP,3.20,2,0,9/2/2015,5,4
327,"Zamora, Jennifer",10010,0,0,0,1,3,4,0,220450,...,Janet King,2.0,Employee Referral,Exceeds,4.60,5,6,2/21/2019,0,16
328,"Zhou, Julia",10043,0,0,0,1,3,3,0,89292,...,Simon Roup,4.0,Employee Referral,Fully Meets,5.00,3,5,2/1/2019,0,11
329,"Zima, Colleen",10271,0,4,0,1,5,3,0,45046,...,David Stanley,14.0,LinkedIn,Fully Meets,4.50,5,0,1/30/2019,0,2

In [ ]:
# select specific data types data  -> select_dtypes()

object_data= hr.select_dtypes('object')
object_data.columns

C:\Users\HP\AppData\Local\Temp\ipykernel_10840\1909490773.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  object_data= hr.select_dtypes('object')

Index(['Employee_Name', 'Position', 'State', 'DOB', 'Gender', 'MaritalDesc',
       'CitizenDesc', 'HispanicLatino', 'RaceDesc', 'DateofHire',
       'DateofTermination', 'TermReason', 'EmploymentStatus', 'Department',
       'ManagerName', 'RecruitmentSource', 'PerformanceScore',
       'LastPerformanceReview_Date'],
      dtype='str')

In [ ]:
object_data=object_data.drop(columns=['DateofTermination','DOB','DateofHire','LastPerformanceReview_Date'])

In [ ]:
object_data.columns

Index(['Employee_Name', 'Position', 'State', 'Gender', 'MaritalDesc',
       'CitizenDesc', 'HispanicLatino', 'RaceDesc', 'TermReason',
       'EmploymentStatus', 'Department', 'ManagerName', 'RecruitmentSource',
       'PerformanceScore'],
      dtype='str')

In [ ]:
object_data['Department'].unique()

<StringArray>
[   'Production       ',                'IT/IS', 'Software Engineering',
        'Admin Offices',                'Sales',     'Executive Office']
Length: 6, dtype: str

In [21]:
# functio  to find wnique values

columns=['Employee_Name', 'Position', 'State', 'Gender', 'MaritalDesc',
       'CitizenDesc', 'HispanicLatino', 'RaceDesc', 'TermReason',
       'EmploymentStatus', 'Department', 'ManagerName', 'RecruitmentSource',
       'PerformanceScore']

def unique_values(dataframes, dara_columns):
    for col in columns:
        print(col)
        print('-'*37)
        unique_data=dataframes[col].unique()
        print(unique_data)
        print('\n')

In [40]:
unique_values(object_data,columns)

Employee_Name
-------------------------------------
<StringArray>
[     'Adinolfi, Wilson  K', 'Ait Sidi, Karthikeyan   ',
        'Akinkuolie, Sarah',             'Alagbe,Trina',
         'Anderson, Carol ',        'Anderson, Linda  ',
          'Andreola, Colby',              'Athwal, Sam',
         'Bachiochi, Linda',       'Bacong, Alejandro ',
 ...
            'Wilber, Barry',            'Wilkes, Annie',
    'Williams, Jacquelyn  ',       'Winthrop, Jordan  ',
            'Wolk, Hang  T',           'Woodson, Jason',
       'Ybarra, Catherine ',         'Zamora, Jennifer',
              'Zhou, Julia',            'Zima, Colleen']
Length: 311, dtype: str


Position
-------------------------------------
<StringArray>
[     'Production Technician I',                      'Sr. DBA',
     'Production Technician II',            'Software Engineer',
                   'IT Support',                 'Data Analyst',
       'Database Administrator',         'Enterprise Architect',
               'Sr. Accountant',           'Production Manager',
                 'Accountant I',           'Area Sales Manager',
 'Software Engineering Manager',                  'BI Director',
       'Director of Operations',         'Sr. Network Engineer',
                'Sales Manager',                 'BI Developer',
         'IT Manager - Support',             'Network Engineer',
                  'IT Director',            'Director of Sales',
     'Administrative Assistant',              'President & CEO',
          'Senior BI Developer',      'Shared Services Manager',
           'IT Manager - Infra',     'Principal Data Architect',
               'Data Architect',              'IT Manager - DB',
                'Data Analyst ',                          'CIO']
Length: 32, dtype: str


State
-------------------------------------
<StringArray>
['MA', 'TX', 'CT', 'VA', 'VT', 'AL', 'WA', 'CA', 'OH', 'IN', 'TN', 'NH', 'RI',
 'PA', 'CO', 'NY', 'UT', 'GA', 'FL', 'NC', 'KY', 'ID', 'NV', 'MT', 'OR', 'ND',
 'AZ', 'ME']
Length: 28, dtype: str


Gender
-------------------------------------
<StringArray>
['M ', 'F']
Length: 2, dtype: str


MaritalDesc
-------------------------------------
<StringArray>
['Single', 'Married', 'Divorced', 'Widowed', 'Separated']
Length: 5, dtype: str


CitizenDesc
-------------------------------------
<StringArray>
['US Citizen', 'Eligible NonCitizen', 'Non-Citizen']
Length: 3, dtype: str


HispanicLatino
-------------------------------------
<StringArray>
['No', 'Yes', 'no', 'yes']
Length: 4, dtype: str


RaceDesc
-------------------------------------
<StringArray>
[                           'White',        'Black or African American',
                'Two or more races',                            'Asian',
 'American Indian or Alaska Native',                         'Hispanic']
Length: 6, dtype: str


TermReason
-------------------------------------
<StringArray>
[               'N/A-StillEmployed',                    'career change',
                            'hours',                 'return to school',
                 'Another position',                          'unhappy',
                       'attendance',                      'performance',
    'Learned that he is a gangster',                         'retiring',
           'relocation out of area',                       'more money',
                         'military',                 'no-call, no-show',
                 'Fatal attraction', 'maternity leave - did not return',
                   'medical issues',                 'gross misconduct']
Length: 18, dtype: str


EmploymentStatus
-------------------------------------
<StringArray>
['Active', 'Voluntarily Terminated', 'Terminated for Cause']
Length: 3, dtype: str


Department
-------------------------------------
<StringArray>
[   'Production       ',                'IT/IS', 'Software Engineering',
        'Admin Offices',                'Sales',     'Executive Office']
Length: 6, dtype: str


ManagerName
-------------------------------------
<StringArray>
[    'Michael Albert',         'Simon Roup',     'Kissy Sullivan',
       'Elijiah Gray',     'Webster Butler',           'Amy Dunn',
    'Alex Sweetwater',      'Ketsia Liebig',     'Brannon Miller',
       'Peter Monroe',      'David Stanley',      'Kelley Spirea',
 'Brandon R. LeBlanc',         'Janet King',         'John Smith',
    'Jennifer Zamora',      'Lynn Daneault',       'Eric Dougall',
     'Debra Houlihan',   'Brian Champaigne', 'Board of Directors']
Length: 21, dtype: str


RecruitmentSource
-------------------------------------
<StringArray>
[               'LinkedIn',                  'Indeed',
           'Google Search',       'Employee Referral',
      'Diversity Job Fair', 'On-line Web application',
           'CareerBuilder',                 'Website',
                   'Other']
Length: 9, dtype: str


PerformanceScore
-------------------------------------
<StringArray>
['Exceeds', 'Fully Meets', 'Needs Improvement', 'PIP']
Length: 4, dtype: str

### Strip whitespace data

In [17]:
object_data['Department']=object_data['Department'].str.strip()

In [18]:
# function to strip data all columns  at once

def removewhitespace(dataframe, datacolumn):
    for col in datacolumn:
        dataframe[col]=dataframe[col].str.strip()

In [19]:
removewhitespace(hr,columns)

In [22]:
object_data['Department'].unique()

<StringArray>
[          'Production',                'IT/IS', 'Software Engineering',
        'Admin Offices',                'Sales',     'Executive Office']
Length: 6, dtype: str

### Replace data

In [ ]:
'''  
-> .str.replace()
Special characters  --> .str.replace(find, replace_value, regex=False/True (default))
Normal Text -> .str.replace(find,replace_value)

'''

In [ ]:
hr